version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "visitors-app"
image_repository= <aws_ecr_URI>>
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
profile = "samdocker"